export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: 'How-to' | 'Privacy' | 'Tips' | 'Comparisons' | 'Platform Guide';
  publishedAt: string;
  updatedAt: string;
  readingTime: string;
  relatedTools: string[];
  relatedArticles: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'compress-image-to-200kb',
    title: 'How to Compress an Image to 200KB Online — Free & Private',
    metaTitle: 'How to Compress an Image to 200KB Online — Free & Private',
    metaDescription: 'Learn how to compress any image to under 200KB without losing visible quality. Free browser-based tool, no upload required. Step-by-step guide.',
    excerpt: 'Many websites and apps have strict file size limits. This guide shows you the easiest ways to compress an image to 200KB — without installing any software.',
    category: 'How-to',
    publishedAt: '2026-02-20',
    updatedAt: '2026-02-20',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'compress-image-to-100kb', 'resize-image'],
    relatedArticles: ['image-privacy-online-tools', 'social-media-image-sizes-2026'],
  },
  {
    slug: 'image-privacy-online-tools',
    title: 'Do Online Image Tools Store Your Photos? The Truth About Image Privacy',
    metaTitle: 'Do Online Image Tools Store Your Photos? The Truth About Image Privacy',
    metaDescription: 'Find out what really happens when you upload images to online tools. Learn how browser-based tools protect your privacy and how to verify it yourself.',
    excerpt: 'You upload a photo to compress it. But what happened to your image in between? This article explains what actually happens — and how to protect yourself.',
    category: 'Privacy',
    publishedAt: '2026-02-20',
    updatedAt: '2026-02-20',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'resize-image', 'rotate-image'],
    relatedArticles: ['compress-image-to-200kb', 'social-media-image-sizes-2026'],
  },
  {
    slug: 'how-to-crop-image-online',
    title: 'How to Crop an Image Online — Free, Instant, No Software Needed',
    metaTitle: 'How to Crop an Image Online — Free, Instant, No Software Needed',
    metaDescription: 'Learn how to crop images online for free in seconds. Choose from preset aspect ratios or draw a custom crop area — no software, no upload required.',
    excerpt: 'Cropping is one of the most common image tasks. Whether you\'re removing an unwanted background or fitting a photo to a specific aspect ratio, this guide shows you how.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['crop-image', 'resize-image', 'compress-image'],
    relatedArticles: ['how-to-add-watermark-to-photo-online', 'social-media-image-sizes-2026', 'image-resolution-pixels-dpi-explained'],
  },
  {
    slug: 'how-to-add-watermark-to-photo-online',
    title: 'How to Add a Watermark to a Photo Online — Free & Private',
    metaTitle: 'How to Add a Watermark to a Photo Online — Free & Private',
    metaDescription: 'Protect your photos with a custom watermark in seconds. Add text or logo watermarks online for free — no upload to server, no software needed.',
    excerpt: 'Whether you\'re a photographer protecting your portfolio or a business owner publishing product photos, watermarks are one of the simplest ways to protect your visual content.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['watermark-image', 'crop-image', 'resize-image'],
    relatedArticles: ['how-to-crop-image-online', 'image-privacy-online-tools', 'compress-image-to-200kb'],
  },
  {
    slug: 'how-to-convert-png-to-jpg-online',
    title: 'How to Convert PNG to JPG Online — Free, Fast, No Upload Required',
    metaTitle: 'How to Convert PNG to JPG Online — Free, Fast, No Upload Required',
    metaDescription: 'Convert PNG, WebP, GIF or BMP to JPG online for free in seconds. No upload to server needed — your files stay private in your browser.',
    excerpt: 'Need to convert a PNG to JPG? Maybe a form only accepts JPG files. Whatever the reason, this guide explains how — and when it actually makes sense to convert.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '4 min',
    relatedTools: ['convert-to-jpg', 'compress-image', 'resize-image'],
    relatedArticles: ['image-format-guide-jpg-png-webp-gif', 'how-to-crop-image-online'],
  },
  {
    slug: 'how-to-blur-photo-online',
    title: 'How to Blur a Photo Online — Censor, Protect Privacy, or Add Depth',
    metaTitle: 'How to Blur a Photo Online — Censor, Protect Privacy, or Add Depth',
    metaDescription: 'Learn how to blur images online for free. Perfect for censoring sensitive info, blurring backgrounds, or creating depth-of-field effects — no software needed.',
    excerpt: 'Blurring an image isn\'t just an artistic effect — it\'s often a practical necessity. This guide covers how to blur images online quickly and for free.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['blur-image', 'crop-image', 'watermark-image'],
    relatedArticles: ['image-privacy-online-tools', 'how-to-crop-image-online', 'compress-image-to-200kb'],
  },
  {
    slug: 'image-resolution-pixels-dpi-explained',
    title: 'Image Resolution Explained: Pixels, DPI, and Why It Matters',
    metaTitle: 'Image Resolution Explained: Pixels, DPI, and Why It Matters',
    metaDescription: 'What\'s the difference between pixels and DPI? Why do images look sharp on screen but blurry when printed? This guide explains image resolution in plain English.',
    excerpt: 'You\'ve probably heard "resolution," "pixels," and "DPI" thrown around when talking about image quality. This guide explains what they actually mean — and when it matters.',
    category: 'Tips',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '6 min',
    relatedTools: ['resize-image', 'compress-image', 'crop-image'],
    relatedArticles: ['image-format-guide-jpg-png-webp-gif', 'social-media-image-sizes-2026', 'how-to-crop-image-online'],
  },
  {
    slug: 'social-media-image-sizes-2026',
    title: 'Image Sizes for Every Social Media Platform in 2026 — The Complete Cheat Sheet',
    metaTitle: 'Social Media Image Sizes 2026 — Complete Cheat Sheet for All Platforms',
    metaDescription: 'Every social media image size in one place — Facebook, Instagram, Twitter/X, YouTube, TikTok, Pinterest, LinkedIn for 2026. Copy the dimensions, resize, and post.',
    excerpt: 'Uploading images at the wrong size means letting the platform crop, compress, or stretch them. This cheat sheet gives you the correct dimensions for every major platform.',
    category: 'Platform Guide',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '7 min',
    relatedTools: ['resize-image', 'crop-image', 'compress-image'],
    relatedArticles: ['social-media-image-sizes-2026', 'image-resolution-pixels-dpi-explained', 'how-to-crop-image-online'],
  },
  {
    slug: 'claude-mcp-image-editing-nanoimage',
    title: 'How to Edit Images Directly in Claude — NanoImage MCP Integration Guide',
    metaTitle: 'Claude MCP Image Editing — Connect NanoImage in 2 Minutes',
    metaDescription: 'Connect NanoImage to Claude in 2 minutes. Compress, resize, crop, convert and edit images directly in your Claude chat — no browser tab switching required.',
    excerpt: 'NanoImage runs as a free MCP server at mcp.nanoimage.net. Connect it to Claude once, and you can compress, resize, crop, and convert images directly inside any conversation.',
    category: 'How-to',
    publishedAt: '2026-02-28',
    updatedAt: '2026-02-28',
    readingTime: '6 min',
    relatedTools: ['compress-image', 'resize-image', 'crop-image', 'convert-to-jpg'],
    relatedArticles: ['compress-image-to-200kb', 'how-to-crop-image-online', 'how-to-convert-png-to-jpg-online'],
  },
  {
    slug: 'image-format-guide-jpg-png-webp-gif',
    title: 'WebP vs JPG vs PNG vs GIF: Which Image Format Should You Use?',
    metaTitle: 'WebP vs JPG vs PNG vs GIF — Complete Image Format Guide 2026',
    metaDescription: 'JPG, PNG, WebP, or GIF — which image format should you use and when? This comprehensive guide compares all four formats with a decision framework and real-world examples.',
    excerpt: 'Different formats make different trade-offs between file size, quality, transparency, and animation. This guide covers all four major formats so you always choose the right one.',
    category: 'Tips',
    publishedAt: '2026-03-30',
    updatedAt: '2026-03-30',
    readingTime: '7 min',
    relatedTools: ['compress-image', 'convert-to-jpg', 'resize-image'],
    relatedArticles: ['how-to-convert-png-to-jpg-online', 'compress-image-to-200kb', 'how-to-crop-image-online'],
  },
  {
    slug: 'fix-sideways-photo',
    title: 'How to Rotate a Sideways Photo Back to Normal',
    metaTitle: 'How to Fix a Sideways Photo Online — Free Rotate Tool | NanoImage',
    metaDescription: 'Photo appearing sideways? Fix it in seconds with NanoImage. Rotate JPEG, PNG, or WebP directly in your browser — no upload, no account, rotation baked into the file.',
    excerpt: 'A photo that looks fine on your phone but appears sideways everywhere else is one of the most common image problems. Here\'s why it happens and how to fix it permanently.',
    category: 'How-to',
    publishedAt: '2026-03-30',
    updatedAt: '2026-03-30',
    readingTime: '5 min',
    relatedTools: ['rotate-image', 'flip-image', 'crop-image'],
    relatedArticles: ['image-privacy-online-tools', 'how-to-crop-image-online', 'compress-image-to-200kb'],
  },
  {
    slug: 'make-meme-online-no-signup',
    title: 'How to Make a Meme Online Without Signing Up',
    metaTitle: 'Free Meme Generator — No Sign Up, No Account Required | NanoImage',
    metaDescription: 'Make memes online without creating an account. Add top and bottom text to any image, adjust font and color, download instantly. 100% free, runs in your browser.',
    excerpt: 'Every major meme generator wants your email. NanoImage\'s meme tool runs entirely in your browser — no account, no sign-up, no marketing emails.',
    category: 'How-to',
    publishedAt: '2026-03-30',
    updatedAt: '2026-03-30',
    readingTime: '5 min',
    relatedTools: ['meme-generator', 'crop-image', 'resize-image'],
    relatedArticles: ['how-to-crop-image-online', 'add-white-border-instagram', 'image-privacy-online-tools'],
  },
  {
    slug: 'add-white-border-instagram',
    title: 'How to Add a White Border to Photos for Instagram',
    metaTitle: 'Add White Border to Photo for Instagram — Free Online Tool | NanoImage',
    metaDescription: 'Add a clean white border to your photos for Instagram in under a minute. Create consistent grid aesthetics with even, Polaroid, or letterbox-style borders — free, no upload.',
    excerpt: 'A consistent white border transforms your Instagram profile grid from cluttered to editorial. Here\'s how to add one in under a minute — directly in your browser.',
    category: 'How-to',
    publishedAt: '2026-03-30',
    updatedAt: '2026-03-30',
    readingTime: '5 min',
    relatedTools: ['add-border-to-image', 'crop-image', 'compress-image'],
    relatedArticles: ['social-media-image-sizes-2026', 'make-meme-online-no-signup', 'how-to-crop-image-online'],
  },
  {
    slug: 'tinypng-vs-nanoimage',
    title: 'TinyPNG vs NanoImage: What\'s the Difference?',
    metaTitle: 'TinyPNG vs NanoImage — Browser-Based Image Compression Compared',
    metaDescription: 'TinyPNG uploads your images to a server. NanoImage compresses in your browser. Compare features, privacy, and compression quality side by side.',
    excerpt: 'TinyPNG is the go-to for image compression, but it uploads every image to its servers. NanoImage compresses entirely in your browser. Here\'s a detailed comparison.',
    category: 'Comparisons',
    publishedAt: '2026-03-31',
    updatedAt: '2026-03-31',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'resize-image', 'crop-image'],
    relatedArticles: ['image-privacy-online-tools', 'compress-image-to-200kb', 'compress-images-for-email'],
  },
  {
    slug: 'resize-photo-passport-visa',
    title: 'How to Resize a Photo for a Visa or Passport Application',
    metaTitle: 'Resize Photo for Passport & Visa — Free Online Tool | NanoImage',
    metaDescription: 'Resize and crop passport or visa photos to exact requirements for US, UK, Schengen, Canada, Australia, and India. Free browser-based tool, no upload needed.',
    excerpt: 'Passport and visa photo requirements are strict. Wrong dimensions or file size means rejection. This guide covers exact specs and how to prepare your photo for free.',
    category: 'How-to',
    publishedAt: '2026-03-31',
    updatedAt: '2026-03-31',
    readingTime: '6 min',
    relatedTools: ['resize-image', 'crop-image', 'compress-image', 'convert-to-jpg'],
    relatedArticles: ['compress-images-for-email', 'image-privacy-online-tools', 'compress-image-to-200kb'],
  },
  {
    slug: 'compress-images-for-email',
    title: 'How to Compress Images for Email Attachments',
    metaTitle: 'Compress Images for Email — Reduce Photo Size for Attachments | NanoImage',
    metaDescription: 'Compress photos for email attachments in seconds. Hit exact file size targets, stay under attachment limits, and keep quality high — free, no upload required.',
    excerpt: 'Email attachment too large? This guide shows you how to compress images to the right size for any email provider — in under a minute, directly in your browser.',
    category: 'How-to',
    publishedAt: '2026-03-31',
    updatedAt: '2026-03-31',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'resize-image', 'convert-to-jpg'],
    relatedArticles: ['compress-image-to-200kb', 'tinypng-vs-nanoimage', 'image-privacy-online-tools'],
  },
  {
    slug: 'convert-photo-black-and-white',
    title: 'How to Make a Photo Black and White Online (Free)',
    metaTitle: 'Convert Photo to Black and White Online — Free Grayscale Tool | NanoImage',
    metaDescription: 'Convert any photo to black and white online for free. Adjust grayscale intensity, preview in real time, and download instantly — no upload, no account needed.',
    excerpt: 'Black and white photography never goes out of style. Convert any colour photo to grayscale instantly in your browser — no software, no account required.',
    category: 'How-to',
    publishedAt: '2026-03-31',
    updatedAt: '2026-03-31',
    readingTime: '5 min',
    relatedTools: ['black-and-white', 'compress-image', 'resize-image'],
    relatedArticles: ['invert-image-colors-online', 'how-to-crop-image-online', 'image-privacy-online-tools'],
  },
  {
    slug: 'invert-image-colors-online',
    title: 'How to Invert Image Colors Online (Free Negative Photo Effect)',
    metaTitle: 'Invert Image Colors Online — Free Negative Effect Tool | NanoImage',
    metaDescription: 'Invert image colors online for free. Create negative photo effects, dark mode previews, or recover film negatives — instant, no upload, no account required.',
    excerpt: 'Inverting an image\'s colours creates a negative effect with more practical uses than you\'d expect. Do it instantly in your browser — one click, no upload.',
    category: 'How-to',
    publishedAt: '2026-03-31',
    updatedAt: '2026-03-31',
    readingTime: '5 min',
    relatedTools: ['invert-colors', 'black-and-white', 'compress-image'],
    relatedArticles: ['convert-photo-black-and-white', 'image-privacy-online-tools', 'how-to-blur-photo-online'],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(currentSlug: string, count = 3): BlogPost[] {
  return blogPosts.filter((p) => p.slug !== currentSlug).slice(0, count);
}

export const blogCategories = ['How-to', 'Privacy', 'Tips', 'Comparisons', 'Platform Guide'] as const;
