export interface BlogPost {
  slug: string;
  title: string;
  metaTitle: string;
  metaDescription: string;
  excerpt: string;
  category: 'How-to' | 'Privacy' | 'Tips' | 'Comparisons' | 'Platform Guide';
  publishedAt: string;
  updatedAt: string;
  readingTime: string;
  relatedTools: string[];
  relatedArticles: string[];
}

export const blogPosts: BlogPost[] = [
  {
    slug: 'compress-image-to-200kb',
    title: 'How to Compress an Image to 200KB Online — Free & Private',
    metaTitle: 'How to Compress an Image to 200KB Online — Free & Private',
    metaDescription: 'Learn how to compress any image to under 200KB without losing visible quality. Free browser-based tool, no upload required. Step-by-step guide.',
    excerpt: 'Many websites and apps have strict file size limits. This guide shows you the easiest ways to compress an image to 200KB — without installing any software.',
    category: 'How-to',
    publishedAt: '2026-02-20',
    updatedAt: '2026-02-20',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'compress-image-to-100kb', 'resize-image'],
    relatedArticles: ['image-privacy-online-tools', 'resize-images-for-platforms'],
  },
  {
    slug: 'image-privacy-online-tools',
    title: 'Do Online Image Tools Store Your Photos? The Truth About Image Privacy',
    metaTitle: 'Do Online Image Tools Store Your Photos? The Truth About Image Privacy',
    metaDescription: 'Find out what really happens when you upload images to online tools. Learn how browser-based tools protect your privacy and how to verify it yourself.',
    excerpt: 'You upload a photo to compress it. But what happened to your image in between? This article explains what actually happens — and how to protect yourself.',
    category: 'Privacy',
    publishedAt: '2026-02-20',
    updatedAt: '2026-02-20',
    readingTime: '5 min',
    relatedTools: ['compress-image', 'resize-image', 'rotate-image'],
    relatedArticles: ['compress-image-to-200kb', 'resize-images-for-platforms'],
  },
  {
    slug: 'resize-images-for-platforms',
    title: 'How to Resize Images for WhatsApp, Email, and Instagram (Free & Easy)',
    metaTitle: 'How to Resize Images for WhatsApp, Email & Instagram — Free Guide',
    metaDescription: 'Get the exact image sizes for WhatsApp, Email, Instagram, Twitter, and more. Free step-by-step guide with a browser-based resize tool.',
    excerpt: 'Every platform has different image requirements. This guide gives you the exact sizes you need — and how to resize quickly without installing any software.',
    category: 'How-to',
    publishedAt: '2026-02-20',
    updatedAt: '2026-02-20',
    readingTime: '5 min',
    relatedTools: ['resize-image', 'compress-image', 'crop-image'],
    relatedArticles: ['compress-image-to-200kb', 'image-privacy-online-tools'],
  },
  {
    slug: 'how-to-crop-image-online',
    title: 'How to Crop an Image Online — Free, Instant, No Software Needed',
    metaTitle: 'How to Crop an Image Online — Free, Instant, No Software Needed',
    metaDescription: 'Learn how to crop images online for free in seconds. Choose from preset aspect ratios or draw a custom crop area — no software, no upload required.',
    excerpt: 'Cropping is one of the most common image tasks. Whether you\'re removing an unwanted background or fitting a photo to a specific aspect ratio, this guide shows you how.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['crop-image', 'resize-image', 'compress-image'],
    relatedArticles: ['how-to-add-watermark-to-photo-online', 'resize-images-for-platforms', 'instagram-image-sizes-guide-2026'],
  },
  {
    slug: 'how-to-add-watermark-to-photo-online',
    title: 'How to Add a Watermark to a Photo Online — Free & Private',
    metaTitle: 'How to Add a Watermark to a Photo Online — Free & Private',
    metaDescription: 'Protect your photos with a custom watermark in seconds. Add text or logo watermarks online for free — no upload to server, no software needed.',
    excerpt: 'Whether you\'re a photographer protecting your portfolio or a business owner publishing product photos, watermarks are one of the simplest ways to protect your visual content.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['watermark-image', 'crop-image', 'resize-image'],
    relatedArticles: ['how-to-crop-image-online', 'image-privacy-online-tools', 'compress-image-to-200kb'],
  },
  {
    slug: 'how-to-convert-png-to-jpg-online',
    title: 'How to Convert PNG to JPG Online — Free, Fast, No Upload Required',
    metaTitle: 'How to Convert PNG to JPG Online — Free, Fast, No Upload Required',
    metaDescription: 'Convert PNG, WebP, GIF or BMP to JPG online for free in seconds. No upload to server needed — your files stay private in your browser.',
    excerpt: 'Need to convert a PNG to JPG? Maybe a form only accepts JPG files. Whatever the reason, this guide explains how — and when it actually makes sense to convert.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '4 min',
    relatedTools: ['convert-to-jpg', 'compress-image', 'resize-image'],
    relatedArticles: ['jpg-vs-png-vs-webp-image-format-guide', 'what-is-webp-image-format', 'how-to-crop-image-online'],
  },
  {
    slug: 'how-to-blur-photo-online',
    title: 'How to Blur a Photo Online — Censor, Protect Privacy, or Add Depth',
    metaTitle: 'How to Blur a Photo Online — Censor, Protect Privacy, or Add Depth',
    metaDescription: 'Learn how to blur images online for free. Perfect for censoring sensitive info, blurring backgrounds, or creating depth-of-field effects — no software needed.',
    excerpt: 'Blurring an image isn\'t just an artistic effect — it\'s often a practical necessity. This guide covers how to blur images online quickly and for free.',
    category: 'How-to',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['blur-image', 'crop-image', 'watermark-image'],
    relatedArticles: ['image-privacy-online-tools', 'how-to-crop-image-online', 'compress-image-to-200kb'],
  },
  {
    slug: 'jpg-vs-png-vs-webp-image-format-guide',
    title: 'JPG vs PNG vs WebP — Which Image Format Should You Use?',
    metaTitle: 'JPG vs PNG vs WebP — Which Image Format Should You Use?',
    metaDescription: 'JPG, PNG, or WebP — which format should you use and when? This plain-English guide explains the differences so you always choose the right format.',
    excerpt: 'Different formats make different trade-offs between file size, quality, and features. Choosing the wrong one can mean unnecessarily large files or visible quality loss.',
    category: 'Tips',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '6 min',
    relatedTools: ['compress-image', 'convert-to-jpg', 'resize-image'],
    relatedArticles: ['what-is-webp-image-format', 'how-to-convert-png-to-jpg-online', 'gif-vs-webp-vs-video-animations'],
  },
  {
    slug: 'image-resolution-pixels-dpi-explained',
    title: 'Image Resolution Explained: Pixels, DPI, and Why It Matters',
    metaTitle: 'Image Resolution Explained: Pixels, DPI, and Why It Matters',
    metaDescription: 'What\'s the difference between pixels and DPI? Why do images look sharp on screen but blurry when printed? This guide explains image resolution in plain English.',
    excerpt: 'You\'ve probably heard "resolution," "pixels," and "DPI" thrown around when talking about image quality. This guide explains what they actually mean — and when it matters.',
    category: 'Tips',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '6 min',
    relatedTools: ['resize-image', 'compress-image', 'crop-image'],
    relatedArticles: ['jpg-vs-png-vs-webp-image-format-guide', 'resize-images-for-platforms', 'instagram-image-sizes-guide-2026'],
  },
  {
    slug: 'what-is-webp-image-format',
    title: 'What Is WebP? The Modern Image Format That Makes Websites Faster',
    metaTitle: 'What Is WebP? The Modern Image Format That Makes Websites Faster',
    metaDescription: 'What is WebP and why are websites using it everywhere? This guide explains WebP, how it compares to JPG and PNG, and when you should (or shouldn\'t) use it.',
    excerpt: 'WebP is increasingly everywhere — but most people don\'t know what it actually is or why it matters. This guide explains WebP in plain terms.',
    category: 'Tips',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['convert-to-jpg', 'compress-image', 'resize-image'],
    relatedArticles: ['jpg-vs-png-vs-webp-image-format-guide', 'gif-vs-webp-vs-video-animations', 'how-to-convert-png-to-jpg-online'],
  },
  {
    slug: 'instagram-image-sizes-guide-2026',
    title: 'Instagram Image Sizes 2026 — The Complete Guide for Every Post Type',
    metaTitle: 'Instagram Image Sizes 2026 — The Complete Guide for Every Post Type',
    metaDescription: 'The complete Instagram image size guide for 2026. Correct dimensions for feed posts, Stories, Reels, carousels, and profile photos — with tips to avoid cropping.',
    excerpt: 'Getting the size wrong on Instagram is frustrating. This guide gives you the exact dimensions for every Instagram post type in 2026, plus practical tips.',
    category: 'Platform Guide',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '6 min',
    relatedTools: ['resize-image', 'crop-image', 'compress-image'],
    relatedArticles: ['social-media-image-sizes-2026', 'how-to-crop-image-online', 'image-resolution-pixels-dpi-explained'],
  },
  {
    slug: 'linkedin-image-sizes-guide-2026',
    title: 'LinkedIn Image Sizes 2026 — Profile, Banner, Post & Company Page',
    metaTitle: 'LinkedIn Image Sizes 2026 — Profile, Banner, Post & Company Page',
    metaDescription: 'Correct LinkedIn image sizes for 2026. Profile photos, banners, post images, company logos, and more — with exact dimensions and tips for a professional appearance.',
    excerpt: 'Using images at the correct dimensions ensures they display sharply and professionally on LinkedIn — not stretched, cropped awkwardly, or blurry.',
    category: 'Platform Guide',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['resize-image', 'crop-image', 'compress-image'],
    relatedArticles: ['social-media-image-sizes-2026', 'instagram-image-sizes-guide-2026', 'image-resolution-pixels-dpi-explained'],
  },
  {
    slug: 'social-media-image-sizes-2026',
    title: 'Image Sizes for Every Social Media Platform in 2026 — The Complete Cheat Sheet',
    metaTitle: 'Social Media Image Sizes 2026 — Complete Cheat Sheet for All Platforms',
    metaDescription: 'Every social media image size in one place — Facebook, Instagram, Twitter/X, YouTube, TikTok, Pinterest, LinkedIn for 2026. Copy the dimensions, resize, and post.',
    excerpt: 'Uploading images at the wrong size means letting the platform crop, compress, or stretch them. This cheat sheet gives you the correct dimensions for every major platform.',
    category: 'Platform Guide',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '7 min',
    relatedTools: ['resize-image', 'crop-image', 'compress-image'],
    relatedArticles: ['instagram-image-sizes-guide-2026', 'linkedin-image-sizes-guide-2026', 'how-to-crop-image-online'],
  },
  {
    slug: 'claude-mcp-image-editing-nanoimage',
    title: 'How to Edit Images Directly in Claude — NanoImage MCP Integration Guide',
    metaTitle: 'Claude MCP Image Editing — Connect NanoImage in 2 Minutes',
    metaDescription: 'Connect NanoImage to Claude in 2 minutes. Compress, resize, crop, convert and edit images directly in your Claude chat — no browser tab switching required.',
    excerpt: 'NanoImage runs as a free MCP server at mcp.nanoimage.net. Connect it to Claude once, and you can compress, resize, crop, and convert images directly inside any conversation.',
    category: 'How-to',
    publishedAt: '2026-02-28',
    updatedAt: '2026-02-28',
    readingTime: '6 min',
    relatedTools: ['compress-image', 'resize-image', 'crop-image', 'convert-to-jpg'],
    relatedArticles: ['compress-image-to-200kb', 'how-to-crop-image-online', 'how-to-convert-png-to-jpg-online'],
  },
  {
    slug: 'gif-vs-webp-vs-video-animations',
    title: 'GIF vs WebP vs Video — Which Format Should You Use for Animations?',
    metaTitle: 'GIF vs WebP vs Video — Which Format Should You Use for Animations?',
    metaDescription: 'Should you use GIF, animated WebP, or video for your animations? This guide compares all three on file size, quality, compatibility, and platform support.',
    excerpt: 'GIFs have been the internet\'s go-to animation format since 1987. But in 2026, animated WebP and short video formats offer significantly better quality at smaller file sizes.',
    category: 'Tips',
    publishedAt: '2026-02-23',
    updatedAt: '2026-02-23',
    readingTime: '5 min',
    relatedTools: ['convert-to-jpg', 'compress-image', 'resize-image'],
    relatedArticles: ['jpg-vs-png-vs-webp-image-format-guide', 'what-is-webp-image-format', 'how-to-convert-png-to-jpg-online'],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getRelatedPosts(currentSlug: string, count = 3): BlogPost[] {
  return blogPosts.filter((p) => p.slug !== currentSlug).slice(0, count);
}

export const blogCategories = ['How-to', 'Privacy', 'Tips', 'Comparisons', 'Platform Guide'] as const;
