// Accepted EN tool-page copy that was live 2026-10-06/07 (Cloudflare deploy e5349c13),
// re-implemented in source on 2026-10-09. Rendered by src/components/tool-seo.tsx.
// HTML strings are trusted, first-party copy (internal links only).

export type RichSeoBlock = { title?: string; html: string }
export type RichSeoSection = { leadHtml?: string; richBlocks?: RichSeoBlock[]; afterCategoryHtml?: string[] }
export type RichFaq = { q: string; a: string; aHtml?: string }

export const EN_TOOL_SEO_2026_10: Record<string, RichSeoSection> = {
  'batch-compress': {
    afterCategoryHtml: [
      'Related guide: <a href="/blog/how-to-bulk-compress-images">How to bulk compress images without losing quality</a>',
    ],
  },
  'black-and-white-image': {
    leadHtml: "To make an image black and white, upload it, choose an output format, click Apply and download. The converter removes the color and keeps the light and shade, so faces, textures and shapes still read clearly in shades of gray. It runs in your browser, so your photo stays on your device. It's free, with no signup and no watermark, for JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to convert a photo to black and white', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Click Upload Image or drag a JPG, PNG, WebP or GIF onto the page, up to 20MB.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Choose an Output format.</strong> It's set to JPG by default. Export as PNG for lossless quality, or keep JPG or WebP for smaller files.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Click Apply.</strong> The whole image converts to black and white, and you'll see \"Done. Your result is ready to download.\"</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Compare.</strong> Open Compare under Preview to check the result against the color original. Reset starts over.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Image to save your black and white photo.</span><img src=\"/assets/tools/black-and-white-image/black-and-white-image-before-after.webp\" alt=\"Before and after: a sunlit old-town street with colorful shutters converted to black and white with NanoImage Black and White Image Converter, keeping the strong light and shadow\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'Why turn a photo black and white?', html: "Color pulls the eye. Without it, people notice shape, light, texture and expression. That's why black and white suits portraits, street photos, architecture and anything with strong shadows. It also gives a picture a timeless look, so a phone snapshot can feel like a print from decades ago. And it hides problems that are hard to fix in color, such as mixed lighting, an orange cast from indoor bulbs, or clothes that clash with the background." },
      { title: 'Black and white portraits', html: 'Portraits are the most common reason people convert photos. In black and white, skin blemishes and redness are less obvious, and the eyes and expression become the focus. Photos taken by a window or in side light work best, because the shadows give the face shape. A flat, front-lit photo can look gray and dull after converting. If that happens, open the result in <a href="/enhance-image">Enhance Image</a> and raise the contrast a little.' },
      { title: 'Give old or family photos a vintage look', html: "Converting a recent photo to black and white makes it match older family prints, which helps when you're putting together a memorial board, an anniversary slideshow or a family history album. It also works the other way: scans of faded color prints often have a pink or yellow tint, and converting them to black and white removes the tint so the picture looks clean again. For scratches, creases and fading, start with <a href=\"/photo-restore\">Photo Restore</a>, then convert." },
      { title: 'Fix a color cast or messy colors', html: "Some photos are hard to save in color. Shots under streetlights turn orange, indoor photos under mixed bulbs go green on one side and yellow on the other, and a noisy night photo can show colored speckles. Converting to black and white removes all of that in one step. What's left is the light and the subject, which is usually what you wanted from the picture in the first place." },
      { title: 'Print documents, forms and photos in grayscale', html: "If you're printing on a black-and-white laser printer, or want to save color ink, converting first lets you see exactly how the page will look before it prints. That helps with photos in a newsletter, images in a school worksheet, or a scanned ID or form. Text and diagrams stay sharp, and you avoid surprises like a red chart line that prints almost invisible. Save as PNG for documents with small text or thin lines." },
      { title: 'Product photos, design and social media', html: 'Black and white can make a set of product photos look consistent when the originals were shot on different days under different light. Designers use grayscale versions of photos as backgrounds behind colored text, or to test whether a layout still works without relying on color. On social media, a black and white post stands out in a grid of bright images. Keep a color copy too, so you can switch back later.' },
      { title: "Black and white vs grayscale: what's the difference?", html: "In everyday use, a \"black and white photo\" means a grayscale photo: one made of many shades of gray between black and white. That's what this converter makes, and it's what you want for photos. A pure black-and-white image, with only black pixels and white pixels and no gray, is different. It's used for stencils, line art, signatures and some printing jobs. Converting a photo that way throws away most of the detail, so a grayscale result is the right choice for almost every picture." },
      { title: 'How to make a picture black and white on iPhone, Word or Photoshop', html: '<span style="display:block;margin-top:.45rem">• <strong>iPhone:</strong> open the photo in Photos, tap Edit, then the filters icon, and choose Mono, Silvertone or Noir.</span><span style="display:block;margin-top:.45rem">• <strong>Microsoft Word:</strong> select the picture, go to Picture Format &gt; Color, and choose Grayscale under Recolor.</span><span style="display:block;margin-top:.45rem">• <strong>Photoshop:</strong> use Image &gt; Adjustments &gt; Black &amp; White, which also lets you control how each color turns to gray.</span><span style="display:block;margin-top:.45rem">These work if you already have the app open. The converter on this page works in any browser on a phone, tablet or computer, with nothing to install, and gives you a file you can download and share right away.</span>' },
      { title: 'Black and white vs invert colors', html: 'Both can make a photo look dramatic, but they do different things. Black and white removes the color and keeps light and dark where they were. <a href="/invert-image-colors">Invert Colors</a> keeps color but flips it, and swaps light and dark, so the photo looks like a film negative. For a stark black and white negative, convert here first and then invert the result.' },
      { title: 'Tips for better black and white photos', html: "<span style=\"display:block;margin-top:.45rem\">• Start with a photo that has strong contrast: bright highlights, real shadows and a clear subject.</span><span style=\"display:block;margin-top:.45rem\">• Simple backgrounds work better than busy ones. Without color, a cluttered background competes with the subject.</span><span style=\"display:block;margin-top:.45rem\">• If the result looks flat, add contrast in <a href=\"/enhance-image\">Enhance Image</a>.</span><span style=\"display:block;margin-top:.45rem\">• Save as PNG if you plan to edit the image again, and JPG or WebP for sharing.</span><span style=\"display:block;margin-top:.45rem\">• To keep one part in color while the rest goes gray, this converter isn't the right tool, because it converts the whole image. For changing one color on purpose, use the <a href=\"/change-color\">Image Color Changer</a>.</span>" },
      { title: 'Is it free and private?', html: "Yes. The black and white converter is free, with no account and no watermark. Your image is processed by your own browser and never uploaded to our servers, so it's safe for personal photos and documents." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: turn a photo into a negative.</span><span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: turn or straighten a photo.</span><span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: pixelate faces, plates or text.</span><span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details.</span>' },
    ],
  },
  'blur-image': {
    leadHtml: "To blur an image, upload it, brush over the area you want to soften, choose a blur type and strength, click Blur Area and download. Only the part you paint gets blurred, and the rest of the photo stays sharp. It runs in your browser, so the picture is never uploaded. It's free, with no signup and no watermark, for JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to blur part of an image', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Click Upload Image or drag a JPG, PNG, WebP or GIF onto the page, up to 20MB.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Select the area.</strong> Under Select Area, paint over what you want to blur with Brush. Change Brush Size to fit, and use Eraser to take back anything you painted by mistake. Clear Selection starts over. To blur the whole photo, press Select All instead.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Choose the blur.</strong> Pick a Blur Type: Gaussian Blur, Soft Blur or Background Blur. Raise Blur Strength until the details can't be read.</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Click Blur Area.</strong> Nothing changes until you click it. When it's done you'll see \"Done. Your result is ready to download.\" Zoom in to check the edges, and use Undo under History if you need a step back.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Image to save the blurred photo.</span><img src=\"/assets/tools/blur-image/blur-image-before-after.webp\" alt=\"Before and after: a woman on a city street kept sharp while the bikes, cafe tables and buildings behind her are softened with NanoImage Blur Image using Background Blur\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'Blur faces in a photo', html: "Blurring faces is the most common reason people use a blur tool. Street photos, school events, protests, parties and group shots often include people who never agreed to be posted, especially children. Paint over each face, including hair and ears, and turn Blur Strength up until the person can't be recognized. At low strength a face can still be identifiable, so check at full zoom. If you want the hiding to be unmistakable, <a href=\"/pixelate-image\">Pixelate Image</a> gives a blocky mosaic instead." },
      { title: 'Blur license plates, addresses and screens', html: "Car listings, dashcam stills, house photos and pictures taken in public can show a plate, a house number, a street sign or a laptop screen in the background. Any of these can reveal who someone is or where they live. Brush over each one and use strong blur. Look closely at reflections too: windows, mirrors, sunglasses and car paint sometimes show more than you'd expect." },
      { title: 'Blur names and details in screenshots', html: "Before sharing a chat, an email, an order page, a bank app or a bug report, blur the names, profile pictures, phone numbers, email addresses and account or order numbers. In support tickets and work docs, blur customer data and anything internal. Soft Blur looks tidy on a screenshot. For passwords, card numbers and one-time codes, don't rely on light blur at all; strong pixelation or cropping the detail out is safer." },
      { title: 'Blur the background and keep the subject sharp', html: "A blurred background makes the subject stand out, the way a portrait-mode phone photo does. It's useful for profile pictures, product photos taken on a messy desk, and portraits shot against a busy street. Paint the subject, choose Background Blur, and the area around it softens while the subject stays in focus. Take your time around hair and the edges of the subject with a smaller brush, because those edges decide whether the effect looks natural. To remove the background completely instead, use <a href=\"/background-remover\">Background Remover</a>." },
      { title: 'Blur a whole photo for a background or wallpaper', html: 'A fully blurred photo makes a soft backdrop for text, which is why it shows up behind quotes on social media, title slides, phone wallpapers and website banners. Press Select All, then Blur Area at a high Blur Strength, and the colors stay while the details melt away, so white or dark text on top is easy to read. Bright, colorful photos give the nicest results.' },
      { title: 'Is blurring enough to hide sensitive information?', html: 'Strong blur hides faces and plates well. Light blur is weaker than it looks: large text and simple shapes can still be read through it, and sharpening tools can sometimes bring back enough to guess a number. Use high Blur Strength for anything private and check the result at full size. Blur also does nothing for the hidden data in the file, such as GPS location and camera details. <a href="/remove-exif">Remove EXIF</a> strips that before you share.' },
      { title: 'Blur vs pixelate: which one should you use?', html: "Both hide details. Blur softens the area so it blends into the photo, which looks more natural on faces and backgrounds. Pixelation turns it into obvious square blocks, which makes it clear something was hidden on purpose and works well for text, numbers and codes. If you're not sure, try both on a copy: blur here, pixelate with <a href=\"/pixelate-image\">Pixelate Image</a>, and keep the one that hides enough without spoiling the picture." },
      { title: 'How to blur an image on iPhone or in Photoshop', html: "<span style=\"display:block;margin-top:.45rem\">• <strong>iPhone:</strong> photos taken in Portrait mode can have their background blur changed after the fact. Open the photo, tap Edit, and adjust the depth (f-number) slider. Regular photos don't have this option.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Photoshop:</strong> select the area, then use Filter &gt; Blur &gt; Gaussian Blur, or Filter &gt; Blur Gallery for more control.</span>The tool on this page works on any photo, on any phone or computer with a browser, with nothing to install." },
      { title: 'Can you unblur an image?', html: 'Usually not. Blurring mixes neighboring pixels together, and the fine detail is lost from that file. Apps that promise to unblur a face are guessing and inventing new detail, not recovering the real one. Keep your original. If you blurred the wrong area, use Undo before downloading, or go back to the original file. If a photo is blurry because of camera shake or focus, <a href="/enhance-image">Enhance Image</a> can help sharpen it.' },
      { title: 'Tips for natural-looking blur', html: "<span style=\"display:block;margin-top:.45rem\">• Paint slightly past the edges of what you're hiding, so no sharp outline is left behind.</span><span style=\"display:block;margin-top:.45rem\">• Use a smaller brush around hair, fingers and text, and lower Hardness for a softer edge that blends in.</span><span style=\"display:block;margin-top:.45rem\">• For privacy, err on the side of stronger blur; for style, lower strength often looks better.</span><span style=\"display:block;margin-top:.45rem\">• After blurring, <a href=\"/compress-image\">Compress Image</a> shrinks the file for sharing.</span>" },
      { title: 'Is it free and private?', html: "Yes. The blur tool is free, with no account and no watermark. Your photo is processed by your own browser and never uploaded to our servers, which matters when you're blurring something precisely because it's private." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: hide faces, plates or text with a mosaic.</span><span style="display:block;margin-top:.45rem">• <a href="/remove-exif">Remove EXIF</a>: remove GPS and camera details before sharing.</span><span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: turn a photo into a negative.</span><span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: turn or straighten a photo.</span>' },
    ],
  },
  'change-color': {
    leadHtml: "An image color changer swaps one color in a photo for another without redrawing it. In NanoImage you upload a picture, brush over the part you want to change, pick a new color or type a hex code, and download. Everything runs in your browser, so the photo never leaves your device, and there's no account or watermark. It works on JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to change the color of an image', html: '<span style="display:block;margin-top:.45rem">1. <strong>Upload your photo.</strong> Drop a JPG, PNG, WebP or GIF into the upload box, up to 20MB. To swap in a different picture later, use Replace image.</span><span style="display:block;margin-top:.45rem">2. <strong>Select the area.</strong> Under Select Area, paint over the part you want to recolor with Brush, and set Brush Size to fit. To catch every spot of that color in the picture, press Select All: it selects everything that matches the color you brushed, within Tolerance. Eraser removes anything you painted by mistake, and Reset Selection clears it.</span><span style="display:block;margin-top:.45rem">3. <strong>Pick a Color Mode.</strong> Solid Color paints a flat color. Tint lays a color over the area and keeps its shading. Hue Replace shifts the color but keeps light and shadow, which looks the most natural on fabric and skin.</span><span style="display:block;margin-top:.45rem">4. <strong>Choose the New Color.</strong> Click the color swatch, or type an exact hex code in the box next to it.</span><span style="display:block;margin-top:.45rem">5. <strong>Fine-tune the edges.</strong> Tolerance decides how far from the painted color a shade can be and still change. Feather softens the border. Zoom in and use a smaller brush around hair and thin edges.</span><span style="display:block;margin-top:.45rem">6. <strong>Download.</strong> When you see "Color changed successfully!", use Undo or Redo if needed, then click Download Image.</span><img src="/assets/tools/change-color/change-color-before-after.webp" alt="Before and after: a red T-shirt recolored to blue with NanoImage Image Color Changer using Hue Replace, with the light background left unchanged" width="1200" height="675" loading="lazy" decoding="async" style="display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px"/>' },
      { title: 'Change the color of clothes or a product', html: "This is the most common job: showing a product in a color you haven't photographed yet, or checking how a shirt looks in navy before you buy it. Brush over the item only, choose Hue Replace so the folds and shadows stay, and pick the new color. If the color spills onto the background, lower Tolerance a little and repaint. Online sellers often export one photo per color variant from a single shot this way." },
      { title: 'Match a logo or brand color exactly', html: 'When a logo, icon or banner has to match brand guidelines, type the hex code in the New Color box instead of eyeballing it. Solid Color gives a clean flat fill for logos and flat graphics. For a photo of a printed sign or packaging, Tint or Hue Replace keeps the texture.' },
      { title: 'Change hair color in a photo', html: 'Want to see yourself as a redhead before booking the salon? Paint over the hair with a medium brush, then switch to a small brush for the hairline and loose strands. Hue Replace keeps the highlights, so the result looks dyed rather than painted. Very fine flyaway hair is the hardest part of any photo, so expect to tidy the edges with the eraser. This is a manual brush tool, not an AI hair filter, which also means nothing is uploaded.' },
      { title: 'Change the background to white or another solid color', html: 'For a plain backdrop, paint the background, pick white or any color, and use Solid Color mode. That suits simple product shots and ID-style photos with an even background. If you need a gradient, a transparent background, or a different scene behind the subject, use <a href="/change-background">Change Background</a>, which is built for that.' },
      { title: 'Change one color everywhere in the image', html: "Sometimes the color you want to change shows up in several places: the red stripes on a flag, every balloon in a party photo, or a brand color repeated across a flyer. Brush a little of it, then press Select All. Everything in the image that matches that color, within Tolerance, gets selected and recolored together, so you don't have to paint each piece. If it grabs too much, lower Tolerance; if it misses some shades, raise it. To recolor the whole photo instead, the <a href=\"/black-and-white-image\">Black and White Image Converter</a> makes a true grayscale version, and <a href=\"/invert-image-colors\">Invert Image Colors</a> flips every color to its opposite." },
      { title: 'Change image color without Photoshop or Canva', html: "Many people search for how to change the color of an image in Photoshop or Canva. For a simple recolor you don't need either. Photoshop does it well, but it means selections, adjustment layers and a subscription. A design app is built for layouts first. A browser color changer gives you a brush, a color picker and a tolerance slider on one screen, free, with nothing to install and no account. For layered, pixel-perfect retouching, a full editor is still the right tool. For \"make this shirt blue,\" this is quicker." },
      { title: 'Try color ideas for designs and social posts', html: "Before you commit to a color scheme, test it on the real image. Recolor a poster background, a phone case mockup or a thumbnail accent three different ways, download each, and compare them side by side. Undo and Reset take you back to the original, so you can try another color without re-uploading. It's a quick way to show a client options or settle a \"blue or green?\" debate with an actual picture instead of a description." },
      { title: 'Tips for clean, natural results', html: '<span style="display:block;margin-top:.45rem">• Start with a sharp, well-lit photo. Strong shadows and reflections are harder to recolor evenly.</span><span style="display:block;margin-top:.45rem">• Use Hue Replace for anything with texture or shading, and Solid Color for flat graphics.</span><span style="display:block;margin-top:.45rem">• Keep Tolerance moderate. Too high and the color leaks into the background, too low and patches get missed.</span><span style="display:block;margin-top:.45rem">• Zoom in on edges and switch to a smaller brush instead of repainting the whole area.</span><span style="display:block;margin-top:.45rem">• Light-to-dark changes, like white to black, look less natural than shifting between similar shades. A Tint plus a second pass often works better.</span>' },
      { title: 'Is it free and private?', html: "Yes. NanoImage's color changer is free, with no signup and no watermark. Your image is processed by your own browser, not on our servers, so it works for product shots, personal photos and client work you'd rather not upload anywhere." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: make a photo negative.</span><span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: straighten or turn a photo.</span><span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: pixelate faces, plates or text.</span><span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details.</span><span style="display:block;margin-top:.45rem">• <a href="/change-background">Change Background</a>: replace the background with a color, gradient or image.</span>' },
    ],
  },
  'flip-image': {
    leadHtml: "To flip an image, upload it, choose Flip Horizontal, Flip Vertical or Flip Both, and download the result. Flipping horizontally swaps left and right, which is the same as making a mirror image. Flipping vertically turns the picture upside down like a reflection in water. NanoImage does it in your browser, so the photo stays on your device. It's free, with no signup and no watermark, and works on JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to flip an image', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Drop a JPG, PNG, WebP or GIF into the upload box, or click to choose a file. Files up to 20MB work.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Choose the direction.</strong> Under Flip Mode, Flip Horizontal mirrors left to right. Flip Vertical mirrors top to bottom. Flip Both does both at once, which looks the same as turning the picture 180°.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Decide on metadata.</strong> Under More Options, \"Keep metadata (EXIF)\" is ticked by default. Untick it if you'd rather not share details like camera model or location with the file.</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Check the preview.</strong> The original and the flipped version sit side by side, so you can switch modes before saving.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Flipped Image. There's no watermark.</span><img src=\"/assets/tools/flip-image/flip-image-before-after.webp\" alt=\"Before and after: a café chalkboard with backwards text flipped horizontally with NanoImage Flip Image so “FRESH COFFEE, OPEN DAILY” reads correctly\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'What is a mirror image?', html: 'A mirror image is a copy of a picture with left and right swapped, exactly what you see in a mirror. The left side of a face appears on the right, and text reads backwards. To make one, use Flip Horizontal. A vertical flip is a different effect. It swaps top and bottom, like a lake reflecting mountains, so the picture ends up upside down. Neither flip changes the size, crop or colors of the image. Only the position of the pixels changes.' },
      { title: 'Flip vs rotate: which one do you need?', html: "Flipping and rotating are easy to mix up. Flipping mirrors the picture, so text comes out backwards and a person facing left now faces right. Rotating turns the whole picture around its center without mirroring it, so text still reads correctly, just at an angle. If a photo is sideways or upside down, you want <a href=\"/rotate-image\">Rotate Image</a>. If it's reversed, like a selfie with backwards writing, you want a flip. One overlap: Flip Both gives the same result as rotating 180°." },
      { title: 'Fix a mirrored selfie', html: "Most phone front cameras show you a mirrored preview, and some save the photo that way too. That's why the writing on your shirt or a sign behind you can come out backwards. Upload the selfie, choose Flip Horizontal, and the text reads normally again. If you prefer the mirrored version of your face because it's the one you see every day, keep the original. It's a matter of taste, not a mistake." },
      { title: 'Fix backwards text in a photo or scan', html: 'Text can come out reversed for other reasons too. Photos taken through a window, scans placed face-down the wrong way, or screenshots from a mirrored video call can all end up backwards. A horizontal flip fixes text that reads right to left. If the text is upside down as well, use Flip Both.' },
      { title: 'Change which way a subject faces in a layout', html: 'Designers flip photos so the subject looks into the page instead of off the edge. A person or product facing toward the headline usually leads the eye better. Flip Horizontal turns a left-facing product shot into a right-facing one without a reshoot. Check for give-away details first: logos, writing, watch faces and parted hair all reveal a flip.' },
      { title: 'Make an iron-on transfer or a print in reverse', html: "Iron-on transfer paper, some T-shirt transfers and certain printmaking methods need the design printed backwards, so it reads correctly once it's pressed onto the fabric. Flip the design horizontally before you print it. Always check your transfer paper's instructions, because some newer papers are made to print without mirroring." },
      { title: 'Create reflections and symmetrical designs', html: 'A vertical flip placed under the original makes a simple water or glass reflection. Lower the opacity of the flipped copy in your editor for a softer look. A horizontal flip placed beside the original gives you a perfectly symmetrical pattern, which works well for banners, wallpapers and kaleidoscope-style art.' },
      { title: 'Flip a photo for a profile picture or social post', html: "A profile picture often sits at the left edge of a page or chat, so a face looking out of the frame can feel awkward. Flip it so you face toward the content. The same trick helps when you pair two photos side by side and want the people in them to face each other. For a new avatar, flip first, then crop to a square with <a href=\"/crop-image\">Crop Image</a> so it fits the platform's frame." },
      { title: 'How to flip an image in Google Docs, Word, Canva or Photoshop', html: "If your picture already lives in another app, it may have a flip option built in:<span style=\"display:block;margin-top:.45rem\">• <strong>Google Docs:</strong> images placed straight into a document can't be flipped. Insert the picture through Insert &gt; Drawing &gt; New, then use Actions &gt; Rotate &gt; Flip horizontally or Flip vertically.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Microsoft Word:</strong> select the picture, open Picture Format &gt; Rotate, and choose Flip Horizontal or Flip Vertical.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Canva:</strong> select the image and click Flip in the toolbar, then choose horizontal or vertical.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Photoshop:</strong> Image &gt; Image Rotation &gt; Flip Canvas Horizontal or Flip Canvas Vertical flips the whole picture.</span><span style=\"display:block;margin-top:.45rem\">If you just need the flipped file, flipping it here first and then inserting it is often quicker, and it works the same everywhere.</span>" },
      { title: 'Does flipping reduce quality?', html: "Flipping only moves pixels. It doesn't resize, crop or recolor anything, so the picture keeps its full resolution. A PNG with a transparent background downloads as a PNG with the transparency kept, so a flipped logo or sticker still sits cleanly on any background. Your image is processed in your own browser and never uploaded to our servers." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: turn a sideways or tilted photo the right way up.</span><span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: make a photo negative.</span><span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: pixelate faces, plates or text.</span><span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details.</span><span style="display:block;margin-top:.45rem">• <a href="/crop-image">Crop Image</a>: trim the edges after flipping.</span>' },
    ],
  },
  'invert-image-colors': {
    leadHtml: "To invert the colors of an image, upload it, choose an output format, click Apply and download. Every color flips to its opposite: black turns white, blue turns orange, green turns magenta. The result looks like an old film negative. NanoImage does it in your browser, so the photo stays on your device. It's free, with no signup and no watermark, for JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to invert image colors', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Click Upload Image or drag a JPG, PNG, WebP or GIF onto the page, up to 20MB.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Choose an Output format.</strong> It's set to JPG by default. Export as PNG to keep exact inverted colors, or keep JPG or WebP for smaller files.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Click Apply.</strong> The colors invert across the whole image, and you'll see \"Done. Your result is ready to download.\"</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Compare.</strong> Use Compare to check the result against the original. Reset starts over.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Image to save the negative.</span><img src=\"/assets/tools/invert-image-colors/invert-image-colors-before-after.webp\" alt=\"Before and after: a field of yellow sunflowers under a blue sky inverted with NanoImage Invert Image Colors, turning the flowers blue and the sky orange\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'What happens when you invert colors?', html: 'Every pixel on screen is a mix of red, green and blue, each on a scale from 0 to 255. Inverting replaces each value with its opposite, 255 minus the original. Pure black (0, 0, 0) becomes pure white (255, 255, 255), and a sky blue becomes a warm orange. Light and dark swap too, so shadows turn bright and highlights turn dark. Because the math is exact, inverting the result a second time gives you back the original picture, as long as you saved it as PNG.' },
      { title: 'Make a photo negative effect', html: 'The negative look is a quick way to make an ordinary photo feel strange and graphic. It works well for album covers, posters, Halloween images and glitch-style social posts. Photos with strong, simple shapes, such as silhouettes, flowers, city skylines and faces with clear lighting, give the most striking negatives. Busy, low-contrast photos tend to turn muddy. For a stark black-and-white negative, convert the photo with the <a href="/black-and-white-image">Black and White Image Converter</a> first, then invert it here.' },
      { title: 'Turn a scanned film negative into a positive', html: "If you've scanned or photographed old negatives, inverting is the first step to seeing the picture. Black-and-white negatives come out well, often good enough to share straight away. Color negatives are trickier. Color film has an orange base layer, so a plain inversion leaves a strong blue-cyan cast. Invert here to see what's on the film, then adjust the colors in a photo editor, or use dedicated scanning software if you're restoring a whole roll. For faded prints rather than negatives, try <a href=\"/photo-restore\">Photo Restore</a>." },
      { title: 'Make screenshots, diagrams and scans dark-mode friendly', html: 'A white screenshot or diagram can glare on a dark slide or in a dark-mode app. Inverting turns black-on-white into white-on-black. That suits code snippets, charts, sketches, handwriting and scanned notes. Colors in the image will shift to their opposites as well, so a red highlight turns cyan. If that matters, recolor it afterwards with the <a href="/change-color">Image Color Changer</a>.' },
      { title: 'Invert a black logo or icon for a dark background', html: "A black logo on a white background disappears on a dark website or a black T-shirt mockup. Invert it to get a white version. This works cleanly for black-and-white artwork. A colored logo will change hue as well, so brand colors won't survive. For those, change just the dark parts with the <a href=\"/change-color\">Image Color Changer</a> instead." },
      { title: 'Save ink when printing dark images', html: 'Slides, charts and screenshots with a black background eat through printer ink and often come out streaky. Invert them before printing and you get dark text and lines on white paper instead. The content stays just as readable, and a page that was mostly black becomes mostly white. This is handy for printing lecture slides, coding tutorials or dark-mode dashboards for a meeting. Save as PNG so thin lines and small text stay crisp.' },
      { title: 'Looking to invert your screen colors instead?', html: "If you want your whole phone or computer screen inverted, not one image, that's an accessibility setting:<span style=\"display:block;margin-top:.45rem\">• <strong>iPhone and iPad:</strong> Settings &gt; Accessibility &gt; Display &amp; Text Size, then turn on Smart Invert or Classic Invert.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Android:</strong> Settings &gt; Accessibility, then Color inversion. The exact menu name varies by phone maker.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Windows 11:</strong> Settings &gt; Accessibility &gt; Color filters, turn on Color filters and choose Inverted.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Mac:</strong> System Settings &gt; Accessibility &gt; Display, then turn on Invert colors.</span><span style=\"display:block;margin-top:.45rem\">Those settings change only how the screen looks. To save an inverted copy of a picture you can share, use the tool above.</span>" },
      { title: 'Invert vs black and white: which one do you need?', html: 'The two are easy to confuse because both can make a photo look dramatic. Black and white removes color but keeps light and dark where they were, so a face still looks like a face. Inverting keeps color but flips every color and every tone, so bright areas go dark and the picture looks like a negative. Use <a href="/black-and-white-image">Black and White Image Converter</a> for a classic grayscale photo, and this tool when you want the negative look or need to swap light and dark.' },
      { title: 'Tips for the best inverted image', html: '<span style="display:block;margin-top:.45rem">• Save as PNG if you might invert the image back later or need exact colors. JPG compression changes colors slightly.</span><span style="display:block;margin-top:.45rem">• High-contrast photos make stronger negatives than flat, hazy ones.</span><span style="display:block;margin-top:.45rem">• To invert only part of a picture, invert a copy and blend it in an editor, or recolor the area with the <a href="/change-color">Image Color Changer</a>.</span><span style="display:block;margin-top:.45rem">• After inverting, <a href="/rotate-image">Rotate Image</a> or <a href="/flip-image">Flip Image</a> can finish the layout.</span>' },
      { title: 'Is it free and private?', html: "Yes. The color inverter is free, with no account and no watermark. The image is processed by your own browser and never uploaded to our servers, so it's safe for personal photos and work documents." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: turn or straighten a photo.</span><span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: pixelate faces, plates or the whole picture.</span><span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details.</span>' },
    ],
  },
  'pixelate-image': {
    leadHtml: "To pixelate an image, upload it, brush over the area you want to hide, pick a pixel size and click Pixelate Area, then download. The brushed area turns into a mosaic of square blocks, so faces, names and numbers can't be read. Everything happens in your browser, so the photo is never uploaded. It's free, with no signup and no watermark, for JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to pixelate an image', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Click Upload Image or drag a JPG, PNG, WebP or GIF onto the page, up to 20MB.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Select the area.</strong> Under Select Area, paint over what you want to hide with Brush. Change Brush Size to fit the area, and use Eraser to take back anything you painted by mistake. Lower Hardness for a softer edge. Clear Selection starts the selection over.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Pick the pixel size.</strong> Drag Pixel Size, or choose a preset: Light (10px), Medium (20px), Strong (40px) or Extreme (80px). Bigger blocks hide more.</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Click Pixelate Area.</strong> Nothing changes until you click it. The selected area turns into a mosaic of square blocks, and you'll see \"Done. Your result is ready to download.\" Zoom in to check the edges.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Image to save the pixelated photo.</span><img src=\"/assets/tools/pixelate-image/pixelate-image-before-after.webp\" alt=\"Before and after: a car licence plate with readable numbers hidden by a square mosaic brush using NanoImage Pixelate Image\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'Hide faces before you post a photo', html: "Group shots, street photos and event pictures often include people who didn't agree to be online, and children whose parents would rather they weren't. Pixelating their faces is the quickest fix. Use a brush a little larger than the face and cover the hair and ears too, since a hairstyle can be just as recognizable. Medium or Strong usually does the job. For a softer look that draws less attention, <a href=\"/blur-image\">Blur Image</a> is the other option." },
      { title: 'Pixelate license plates, house numbers and addresses', html: 'Car photos for a sale listing, a dashcam clip still or a picture of your new front door can give away more than you meant to share. A plate number can be linked to the owner, and a house number plus a street view gives away where you live. Brush over the plate or number, pick Strong, and check at full zoom that no digit can still be read. Do the same with street signs in the background if the location matters.' },
      { title: 'Redact names and numbers in screenshots', html: 'Screenshots of chats, emails, bank apps, order pages and boarding passes are full of personal details. Before posting one in a group chat, a forum or a support ticket, pixelate names, profile pictures, phone numbers, email addresses, account and order numbers, and any barcodes or QR codes. A QR code or barcode on a boarding pass or ticket can be scanned straight from a photo, so cover the whole code, not just part of it.' },
      { title: 'Clean up listing photos before you post them', html: "Photos for a rental ad, a home sale or a marketplace listing often catch more than the item. Family photos on the wall, letters with your address on the counter, a laptop screen, a calendar, or your face reflected in a mirror, a TV or a window all end up online with the listing. Go through each photo at full size before posting and pixelate anything personal. It takes a minute, and buyers and renters don't need any of it to judge the room or the item." },
      { title: 'Is pixelation safe for passwords and sensitive text?', html: 'For faces and plates, strong pixelation works well. For short text such as passwords, card numbers or one-time codes, be more careful. Researchers have shown that text pixelated with small blocks can sometimes be guessed back, because each block still holds the average color of the letters underneath. Use Strong or Extreme so each block covers several characters, and for anything truly secret, crop it out or cover it with a solid block of color instead. Also remember that the original file, and its metadata, still exist. <a href="/remove-exif">Remove EXIF</a> strips GPS location and camera details before you share.' },
      { title: 'Pixelate vs blur: which should you use?', html: "Both hide details, but they look different. Pixelation leaves obvious square blocks, which makes it clear something was hidden on purpose. That suits text, numbers, codes and documents. Blur softens the area so it blends in, which looks more natural on faces and backgrounds. If you're not sure, try both: pixelate here, blur with <a href=\"/blur-image\">Blur Image</a>, and keep the one that hides enough without spoiling the photo." },
      { title: 'Can you un-pixelate an image?', html: "Usually not. Pixelating replaces the detail in each block with a single color, so the original information is gone from that file. Tools that claim to \"unpixelate\" a face are guessing and inventing new detail, not recovering the real one. That's why you should keep your unedited original. If you pixelated the wrong area, go back to the original file and do it again. If a photo just looks blocky because it was saved too small or compressed, that's a different problem, and <a href=\"/enhance-image\">Enhance Image</a> can help sharpen it." },
      { title: 'Tips for clean pixelation', html: "<span style=\"display:block;margin-top:.45rem\">• Brush slightly past the edges of what you're hiding. Mosaic blocks near the border can leave a few readable pixels.</span><span style=\"display:block;margin-top:.45rem\">• Zoom in after you click Pixelate Area and look for anything still legible.</span><span style=\"display:block;margin-top:.45rem\">• Bigger is safer. When in doubt, step up one preset.</span><span style=\"display:block;margin-top:.45rem\">• Save a copy of the original before you start.</span><span style=\"display:block;margin-top:.45rem\">• Check the background as well as the subject. Name tags, screens, mail and reflections are easy to miss on the first pass.</span><span style=\"display:block;margin-top:.45rem\">• Pixelate only what needs hiding. A photo with small, tidy mosaic patches still looks good, while one covered in blocks stops being worth sharing.</span><span style=\"display:block;margin-top:.45rem\">• After pixelating, <a href=\"/flip-image\">Flip Image</a> or <a href=\"/rotate-image\">Rotate Image</a> can finish the layout.</span>" },
      { title: 'Is it free and private?', html: "Yes. The pixelator is free, with no account and no watermark. Your photo is processed by your own browser and never uploaded to our servers, which matters when the reason you're pixelating is privacy in the first place." },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details more softly.</span><span style="display:block;margin-top:.45rem">• <a href="/remove-exif">Remove EXIF</a>: remove GPS and camera details before sharing.</span><span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: turn a photo into a negative.</span><span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/rotate-image">Rotate Image</a>: turn or straighten a photo.</span>' },
    ],
  },
  'rotate-image': {
    leadHtml: "To rotate an image, upload it, click 90° Left, 90° Right or 180°, or drag the Angle slider for an exact degree, then click Download Rotated Image. NanoImage's image rotator works in your browser, so the photo never leaves your device. It handles quick fixes like a sideways phone photo and finer ones like a horizon that's two degrees off. It's free, with no signup and no watermark, for JPG, PNG, WebP and GIF files up to 20MB.",
    richBlocks: [
      { title: 'How to rotate an image', html: "<span style=\"display:block;margin-top:.45rem\">1. <strong>Upload your image.</strong> Drop a JPG, PNG, WebP or GIF into the upload box, up to 20MB.</span><span style=\"display:block;margin-top:.45rem\">2. <strong>Turn it.</strong> Use 90° Left or 90° Right for a sideways photo, or 180° for one that's upside down.</span><span style=\"display:block;margin-top:.45rem\">3. <strong>Straighten it, if needed.</strong> Drag the Angle slider anywhere from -180° to 180° to level a tilted horizon or a crooked scan. If the picture tilts the wrong way, go the other direction (a horizon that drops to the right usually needs a positive angle). Flip Horizontal and Flip Vertical are there too if you also need a mirror image.</span><span style=\"display:block;margin-top:.45rem\">4. <strong>Handle the corners.</strong> A custom angle leaves empty corners. Under Canvas Options, set Fit to Expand Canvas (Keep All) to keep the whole picture on a bigger canvas, with the corners filled by the Background color (white by default), or to Crop to original size to keep the original dimensions and trim the corners away. Reset All takes you back to the start.</span><span style=\"display:block;margin-top:.45rem\">5. <strong>Download.</strong> Click Download Rotated Image. The file keeps its original format, so a PNG comes back as a PNG.</span><img src=\"/assets/tools/rotate-image/rotate-image-before-after.webp\" alt=\"Before and after: a sunset sea photo with a tilted horizon straightened by rotating it 4° with NanoImage Rotate Image, leaving white corners from the expanded canvas\" width=\"1200\" height=\"675\" loading=\"lazy\" decoding=\"async\" style=\"display:block;width:100%;max-width:1200px;height:auto;margin-top:1rem;border-radius:14px\"/>" },
      { title: 'Fix a sideways or upside-down phone photo', html: 'Phones store a small orientation note inside each photo instead of turning the pixels. Your gallery reads that note and shows the photo upright. Some websites, email clients and older programs ignore it, so the same photo shows up sideways once you upload it. Rotating the image here turns the actual pixels, so it stays the right way up everywhere. One or two clicks of 90° Left or 90° Right is usually all it takes.' },
      { title: 'Straighten a tilted horizon or crooked photo', html: "A beach shot where the sea slopes downhill, or a building that leans, looks off even when people can't say why. Drag the angle slider a degree or two at a time until the horizon or a vertical edge lines up. Then choose Crop to original size to trim the empty corners, or Expand Canvas if you'd rather crop it yourself later with <a href=\"/crop-image\">Crop Image</a>." },
      { title: 'Rotate scanned documents, receipts and homework', html: 'Scans and photos of paper often come out sideways or a little skewed. That makes them hard to read on screen and awkward to submit. Turn the page with the 90° buttons, then nudge the slider until the lines of text run level. If you plan to combine several pages, rotate each one first and then join them with <a href="/image-to-pdf">Image to PDF</a>.' },
      { title: 'Switch between portrait and landscape', html: "Sometimes a photo is upright but the wrong shape for where it's going, like a tall phone photo for a wide slide or a landscape shot for a phone wallpaper. Rotating by 90° swaps the width and height. Expand Canvas (Keep All) makes sure nothing gets cut off. Afterwards, <a href=\"/resize-image\">Resize Image</a> gets it to the exact pixel size you need." },
      { title: 'Rotate product photos for listings', html: 'Marketplaces show your first photo as a thumbnail, and a crooked product looks careless next to the competition. Straighten each shot so the product sits level, and use a white background color for the corners so it matches a typical clean listing. Keep the same angle fix across a set of photos so they look consistent in the gallery.' },
      { title: 'Tilt a logo, sticker or graphic for a design', html: "Not every rotation is a fix. A sticker set at 12°, a \"SALE\" badge tipped onto a product shot, or a photo laid at an angle in a scrapbook-style collage all start as straight images. Set the exact angle with the slider so several pieces match. Use Expand Canvas so the corners of the graphic aren't clipped, then place the result in your design. Write the angle down if you'll need the same tilt again later." },
      { title: 'How to rotate an image in Word, Photoshop, Windows or Mac', html: "<span style=\"display:block;margin-top:.45rem\">If the picture is already open somewhere else, there's usually a built-in option:</span><span style=\"display:block;margin-top:.45rem\">• <strong>Microsoft Word:</strong> select the picture, go to Picture Format &gt; Rotate, and choose Rotate Right 90° or Rotate Left 90°. More Rotation Options lets you type an angle.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Photoshop:</strong> Image &gt; Image Rotation offers 90° Clockwise, 90° Counter Clockwise, 180° or Arbitrary for a custom angle.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Windows Photos:</strong> open the photo and click Rotate, or press Ctrl+R.</span><span style=\"display:block;margin-top:.45rem\">• <strong>Mac Preview:</strong> Tools &gt; Rotate Left or Rotate Right, or press Command+L / Command+R.</span>These change the file inside that app. If you want one rotated copy that looks right everywhere you upload it, rotating it here and downloading the result is the simplest route." },
      { title: "Rotate vs flip: what's the difference?", html: "Rotating turns the whole picture around its center, and text still reads correctly, just at an angle. Flipping mirrors the picture, so text comes out backwards. If a photo is sideways or tilted, rotate it. If it's reversed, like a selfie with backwards writing, use <a href=\"/flip-image\">Flip Image</a>. This tool also has Flip Horizontal and Flip Vertical buttons, so you can do both in one go." },
      { title: 'Does rotating reduce image quality?', html: 'Turning by 90° or 180° just rearranges pixels, so nothing is lost. A custom angle has to redraw the pixels on a new grid, which can soften very fine detail slightly, so rotate once rather than in many small steps. For JPGs, export once at the end instead of re-saving over and over. Everything runs in your browser, and the file is never uploaded.' },
      { title: 'More ways to edit your photo', html: '<span style="display:block;margin-top:.45rem">• <a href="/flip-image">Flip Image</a>: mirror a photo horizontally or vertically.</span><span style="display:block;margin-top:.45rem">• <a href="/change-color">Image Color Changer</a>: recolor clothes, logos or backgrounds.</span><span style="display:block;margin-top:.45rem">• <a href="/invert-image-colors">Invert Image Colors</a>: make a photo negative.</span><span style="display:block;margin-top:.45rem">• <a href="/black-and-white-image">Black and White Image Converter</a>: turn a photo grayscale.</span><span style="display:block;margin-top:.45rem">• <a href="/pixelate-image">Pixelate Image</a>: pixelate faces, plates or text.</span><span style="display:block;margin-top:.45rem">• <a href="/blur-image">Blur Image</a>: blur a background or hide details.</span><span style="display:block;margin-top:.45rem">• <a href="/crop-image">Crop Image</a>: trim empty corners after rotating.</span>' },
    ],
  },
}

export const EN_TOOL_FAQS_2026_10: Record<string, RichFaq[]> = {
  'batch-compress': [
    { q: 'How do I compress multiple images at once?', a: 'Open NanoImage Batch Compress. Upload or drag and drop up to 20 images (JPG, PNG, WebP, or GIF, max 20MB each). Adjust quality if needed, preview the results, then click Compress & Download ZIP. Everything runs in your browser—files are not uploaded to our servers.', aHtml: 'Open <a href="/batch-compress">NanoImage Batch Compress</a>. Upload or drag and drop up to 20 images (JPG, PNG, WebP, or GIF, max 20MB each). Adjust quality if needed, preview the results, then click <strong>Compress &amp; Download ZIP</strong>. Everything runs in your browser—files are not uploaded to our servers.' },
    { q: 'Does this bulk image compressor work on Mac and Windows?', a: 'Yes. NanoImage runs in your browser on Mac, Windows, and other desktops. You do not install an app. Use Chrome, Firefox, Safari, or Edge, open the batch compress page, and compress locally the same way on either OS.' },
    { q: 'Will bulk compression ruin image quality?', a: 'Not if you pick a sensible quality setting. Lower quality makes smaller files; higher quality keeps more detail. Use the preview and the original vs compressed size totals before you download. Aim for the smallest file that still looks good for your site, email, or product photos—not the absolute lowest setting every time.' },
    { q: 'What are the limits for batch compression?', a: 'You can compress up to 20 images per batch. Each file can be up to 20MB. Supported formats are JPG, PNG, WebP, and GIF. After compression, download everything as a ZIP, or reset and start a new batch.', aHtml: 'You can compress up to <strong>20 images</strong> per batch. Each file can be up to <strong>20MB</strong>. Supported formats are <strong>JPG, PNG, WebP, and GIF</strong>. After compression, download everything as a ZIP, or reset and start a new batch.' },
    { q: 'How is batch compress different from compressing one image?', a: 'Single-image compress is fine for one file. Batch compress is faster when you have a folder of product shots, blog images, or screenshots. You set quality once, see totals for the whole batch, and get one ZIP instead of downloading file by file. For one file, use Compress Image.', aHtml: 'Single-image compress is fine for one file. Batch compress is faster when you have a folder of product shots, blog images, or screenshots. You set quality once, see totals for the whole batch, and get one ZIP instead of downloading file by file. For one file, use <a href="/compress-image">Compress Image</a>.' },
    { q: 'Are my images uploaded when I use the bulk compressor?', a: 'No. Your images are processed in your browser. NanoImage does not upload them to our servers. That keeps batches private and works offline once the page is loaded (network only needed to open the tool).' },
  ],
  'black-and-white-image': [
    { q: 'How do I make an image black and white online?', a: 'Upload the photo, choose PNG, JPG or WebP, click Apply, and download. The converter removes the color and keeps the light and shade.' },
    { q: 'Will converting to black and white reduce image quality?', a: 'No. The image keeps its original resolution. Save as PNG to keep every gray tone exact, or JPG or WebP for a smaller file.' },
    { q: 'What is the difference between black and white and grayscale?', a: 'A black and white photo is usually grayscale, made of many shades of gray. A pure black-and-white image has only black and white pixels and is used for stencils and line art. This tool makes grayscale.' },
    { q: 'Can I make a black and white photo look more dramatic?', a: 'Yes. Start with a high-contrast photo, then open the result in Enhance Image to raise contrast and brightness.' },
    { q: 'Is this black and white converter free, and is my photo uploaded?', a: "It's free with no signup and no watermark. Your photo is processed in your browser and never uploaded." },
  ],
  'blur-image': [
    { q: 'How do I blur part of an image?', a: 'Upload it, brush over the area, choose a Blur Type and Blur Strength, click Blur Area, and download. Only the painted area is blurred.' },
    { q: 'How do I blur a face in a photo for free?', a: "Paint over the face, including hair, raise Blur Strength until it can't be recognized, click Blur Area, and download. It's free and runs in your browser." },
    { q: 'Can I blur the background and keep the subject sharp?', a: 'Yes. Paint the subject, choose Background Blur, and the area around it softens while the subject stays in focus.' },
    { q: 'Can I unblur an image?', a: "No. Blurring mixes pixels together, so the detail can't be recovered from that file. Use Undo before downloading, or keep your original." },
    { q: 'Is this blur tool free, and is my photo uploaded?', a: "It's free with no signup and no watermark. Your photo is processed in your browser and never uploaded." },
  ],
  'change-color': [
    { q: 'Is this image color changer free?', a: "Yes. It's free with no signup and no watermark, and it runs entirely in your browser." },
    { q: 'How do I change one color without changing the whole photo?', a: 'Paint only that area with the brush, pick the new color, and lower Tolerance if other parts start to change. The eraser removes anything you selected by mistake.' },
    { q: 'Can I change the color to an exact hex code?', a: 'Yes. Type the hex code in the color picker. Solid Color mode gives an exact flat match, while Tint and Hue Replace keep the shading.' },
    { q: 'Can I change hair or clothing color in a photo?', a: 'Yes. Brush over the hair or clothing and use Hue Replace to keep highlights and folds. Fine hair edges may need a small brush and some cleanup with the eraser.' },
    { q: 'Which formats can I upload, and are my photos uploaded?', a: 'JPG, PNG, WebP and GIF up to 20MB. Photos are processed locally in your browser and never sent to our servers.' },
  ],
  'flip-image': [
    { q: 'How do I flip an image for free?', a: "Upload it to NanoImage Flip Image, choose Flip Horizontal, Flip Vertical or Flip Both, and download. It's free with no signup and no watermark." },
    { q: 'How do I make a mirror image of a photo?', a: 'Use Flip Horizontal. It swaps left and right, which is exactly what a mirror does.' },
    { q: "What's the difference between flipping and rotating an image?", a: 'Flipping mirrors the picture, so text reads backwards. Rotating turns it around its center without mirroring. Flip Both is the same as rotating 180°.' },
    { q: 'Why does my selfie look backwards, and how do I fix it?', a: 'Many front cameras save a mirrored photo. Flip it horizontally and any text in the shot will read normally again.' },
    { q: 'Does flipping an image reduce its quality, and is it uploaded?', a: 'No. Flipping only moves pixels and keeps the full resolution. The image is processed in your browser and never uploaded.' },
  ],
  'invert-image-colors': [
    { q: 'How do I invert the colors of an image?', a: 'Upload it, choose PNG, JPG or WebP, click Apply, and download. Every color flips to its opposite, like a photo negative.' },
    { q: 'What does inverting colors do?', a: 'It replaces each color with its opposite on the color wheel and swaps light and dark. Black becomes white, blue becomes orange. Inverting twice restores the original.' },
    { q: 'Can I turn a film negative into a normal photo?', a: "Yes for black-and-white negatives, which invert cleanly. Color negatives come out with a blue cast because of the film's orange base, so they need color correction afterwards." },
    { q: 'How do I invert colors on my iPhone or computer screen?', a: "That's an accessibility setting. On iPhone go to Settings > Accessibility > Display & Text Size. On Windows 11 use Settings > Accessibility > Color filters. On Mac use System Settings > Accessibility > Display." },
    { q: 'Is this color inverter free, and is my image uploaded?', a: "It's free with no signup and no watermark. Your image is processed in your browser and never uploaded." },
  ],
  'pixelate-image': [
    { q: 'How do I pixelate part of an image?', a: 'Upload it, brush over the area, choose a Pixel Size or preset, click Pixelate Area, and download. Only the brushed area turns into a mosaic.' },
    { q: 'How do I pixelate a face or license plate?', a: 'Brush over the face or plate with a slightly larger brush, choose Strong, and click Pixelate Area. Zoom in to check nothing can still be read.' },
    { q: 'Can I un-pixelate an image?', a: "No. Pixelation replaces detail with blocks of a single color, so it can't be recovered from that file. Keep your original and edit it again instead." },
    { q: 'What is the difference between pixelate and blur?', a: 'Pixelate turns an area into square blocks, which is best for text, numbers and codes. Blur softens it so it blends in, which looks more natural on faces and backgrounds.' },
    { q: 'Is this pixelate tool free, and is my photo uploaded?', a: "It's free with no signup and no watermark. Your photo is processed in your browser and never uploaded." },
  ],
  'rotate-image': [
    { q: 'How do I rotate an image for free?', a: "Upload it to NanoImage Rotate Image, click 90° Left, 90° Right or 180°, or drag the slider for a custom angle, then download. It's free with no signup and no watermark." },
    { q: 'Can I rotate an image by a custom angle?', a: 'Yes. The Angle slider goes from -180° to 180°, so you can straighten a horizon or a crooked scan by just a few degrees.' },
    { q: 'Why are there empty corners after rotating?', a: 'A custom angle tilts the rectangle, which leaves gaps. Choose Expand Canvas to keep everything and fill the corners with a background color, or Crop to original size to trim them.' },
    { q: 'Why does my photo show sideways after I upload it?', a: 'Phones often save an orientation tag instead of turning the pixels, and some sites ignore it. Rotate the image here and download it so the pixels themselves are upright.' },
    { q: 'Does rotating an image reduce quality, and is it uploaded?', a: '90° and 180° turns lose nothing. A custom angle may soften fine detail slightly. The image is processed in your browser and never uploaded.' },
  ],
}

/** EN-only H1 / intro line overrides for pages whose hub cards keep the short toolsData copy. */
export const EN_TOOL_PAGE_HERO_2026_10: Record<string, { h1: string; line: string; lineHtml?: string }> = {
  'batch-compress': { h1: 'Bulk Image Compressor', line: 'Compress multiple images at once. Free bulk image compressor for JPG, PNG, WebP, and GIF.' },
  'gif-maker': { h1: 'Free GIF Maker — Create Animated GIFs from Images', line: 'A GIF maker turns still images into an animated GIF. NanoImage’s free GIF maker runs in your browser: add frames, set speed/size/loops, and download without a watermark. Free, no account. To shrink an existing GIF for Discord or a size cap, use the GIF Compressor (separate tool).', lineHtml: 'A GIF maker turns still images into an animated GIF. NanoImage’s free GIF maker runs in your browser: add frames, set speed/size/loops, and download without a watermark. Free, no account. To shrink an existing GIF for Discord or a size cap, use the <a href="/gif-compressor">GIF Compressor</a> (separate tool).' },
}
